import axios from "axios";
import { config } from "./config";
import { getToken } from "./tokenStore";

function client(agentName: string) {
  const token = getToken(agentName);

  return axios.create({
    baseURL: `${config.giteaBase}/api/v1`,
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });
}

export async function createRepo(name: string, description: string) {
  const res = await client("planner-1").post(`/user/repos`, {
    name,
    description,
    private: false,
    auto_init: true,
  });

  // console.log(res.data)
  return res.data;
}

export async function searchReposWithIssues() {
  const res = await client("builder-1").get(
    `/repos/search?has_issues=true&is_private=false&limit=50`,
  );

  // console.log(res.data)

  return res.data.data; // Gitea returns { ok, data }
}

export async function getIssuesForRepo(owner: string, repo: string) {
  const res = await client("builder-1").get(
    `/repos/${owner}/${repo}/issues?state=open`,
  );

  return res.data;
}

export async function createIssue(
  title: string,
  body: string,
  issuesCreator: string,
  repo: string,
) {
  await client("planner-1").post(`/repos/${issuesCreator}/${repo}/issues`, {
    title,
    body,
  });
}

export async function createPR(
  owner: string,
  repo: string,
  title: string,
  head: string,
) {
  await client("builder-1").post(`/repos/${owner}/${repo}/pulls`, {
    title,
    head,
    base: "main",
    body: "Generated by autonomous builder agent",
  });
}

export async function getPRs() {
  const res = await client("reviewer-1").get(
    `/repos/${config.owner}/${config.repo}/pulls?state=open`,
  );
  return res.data;
}

export async function commentPR(index: number, body: string) {
  await client("reviewer-1").post(
    `/repos/${config.owner}/${config.repo}/issues/${index}/comments`,
    {
      body,
    },
  );
}

export async function mergePR(index: number) {
  await client("reviewer-1").post(
    `/repos/${config.owner}/${config.repo}/pulls/${index}/merge`,
  );
}
