import axios from "axios";
import { config } from "./config";
import { getToken } from "./tokenStore";

function client(agentName: string) {
  const token = getToken(agentName);

  return axios.create({
    baseURL: `${config.API_BASE_URL}/api/v1`,
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });
}

export async function createRepo(
  name: string,
  description: string,
  owner,
  reviewer: string,
) {
  const res = await client(owner).post(`/user/repos`, {
    name,
    description,
    private: false,
    auto_init: true,
  });

  // After creating repo, we need to add 1 as collaborator so it can review PRs, comment and merge them.
  await client(owner).put(
    `/repos/${res.data.owner.username}/${res.data.name}/collaborators/${reviewer}`,
  );

  return res.data;
}

export async function searchReposWithIssues() {
  const res = await client(config.builderAgentName).get(
    `/repos/search?has_issues=true&is_private=false&limit=50`,
  );

  // console.log(res.data)

  return res.data.data; // Gitea returns { ok, data }
}

export async function searchReposWithIssuesForPlanner() {
  const res = await client(config.builderAgentName).get(
    `/repos/search?has_issues=true&is_private=false&limit=50`,
  );

  const allRepos = res.data.data; // Gitea returns { ok, data }

  // Filter to only return repos owned by the planner
  const plannerRepos = allRepos.filter(
    (repo: any) => repo.owner.login === config.plannerAgentName,
  );

  return plannerRepos;
}

export async function getIssuesForRepo(
  owner: string,
  repo: string,
  builderName: string,
) {
  const res = await client(builderName).get(
    `/repos/${owner}/${repo}/issues?state=open`,
  );

  return res.data;
}

export async function createIssue(
  title: string,
  body: string,
  issuesCreator: string,
  repo: string,
) {
  await client(issuesCreator).post(`/repos/${issuesCreator}/${repo}/issues`, {
    title,
    body,
  });
}

export async function createPR(
  repoOwner: string,
  repoName: string,
  title: string,
  headBranch: string,
  forkOwner?: string,
  body?: string,
) {
  const agentName = config.builderAgentName; //
  const api = client(agentName);

  try {
    // Head must be forkOwner:branch if different from original repo
    const head =
      forkOwner && forkOwner !== repoOwner
        ? `${forkOwner}:${headBranch}`
        : headBranch;

    const res = await api.post(`/repos/${repoOwner}/${repoName}/pulls`, {
      title,
      head,
      base: "main", // assuming default branch is main
      body: body || "Generated by AI agent",
    });

    console.log(`✅ PR created: ${head} -> ${repoOwner}/main`);
    return res.data;
  } catch (err: any) {
    console.error("❌ Failed to create PR:", err.response?.data || err.message);
    throw err;
  }
}

// List all repos reviewer has access to
export async function getAllReposForReviewer() {
  const res = await client(config.reviewerAgentName).get(
    `/user/repos?limit=100`,
  );
  return res.data; // returns array of { owner, name, ... }
}

// Get all PRs for a given repo
export async function getPRs(owner: string, repo: string) {
  const res = await client(config.reviewerAgentName).get(
    `/repos/${owner}/${repo}/pulls?state=open`,
  );
  return res.data;
}

export async function commentPR(
  owner: string,
  repo: string,
  prNumber: number,
  body: string,
) {
  await client(config.reviewerAgentName).post(
    `/repos/${owner}/${repo}/issues/${prNumber}/comments`,
    { body },
  );
}

export async function mergePR(owner: string, repo: string, prNumber: number) {
  await client(config.reviewerAgentName).post(
    `/repos/${owner}/${repo}/pulls/${prNumber}/merge`,
    { Do: "merge" },
  );
}

/**
 * Close an issue by setting its state to "closed"
 */
export async function closeIssue(
  owner: string,
  repo: string,
  issueNumber: number,
) {
  try {
    await client(config.reviewerAgentName).patch(
      `/repos/${owner}/${repo}/issues/${issueNumber}`,
      { state: "closed" },
    );
    console.log(`✅ Issue #${issueNumber} closed in ${owner}/${repo}`);
  } catch (err: any) {
    console.error(
      `❌ Failed to close issue #${issueNumber}:`,
      err.response?.data || err.message,
    );
  }
}

export async function forkRepo(owner: string, repo: string) {
  const agentName = config.builderAgentName;
  const username = agentName;
  const api = client(agentName);

  try {
    // 1️⃣ Check if fork already exists
    try {
      const existingFork = await api.get(`/repos/${username}/${repo}`);
      console.log(`ℹ️ Fork already exists: ${username}/${repo}`);
      return existingFork.data;
    } catch (err: any) {
      if (err.response?.status !== 404) {
        console.error(
          "❌ Error checking existing fork:",
          err.response?.data || err.message,
        );
        return null; // don't crash builder
      }
    }

    // 2️⃣ Create fork
    const res = await api.post(`/repos/${owner}/${repo}/forks`);
    console.log(
      `✅ Fork created: ${owner}/${repo} -> ${res.data.owner.login}/${repo}`,
    );

    return res.data;
  } catch (err: any) {
    console.error("❌ Failed to fork repo:", err.response?.data || err.message);
    return null; // graceful failure
  }
}
